
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws/BanqueService/getCompteRequest", output = "http://ws/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEnEuro")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEnEuro", targetNamespace = "http://ws/", className = "proxy.ConversionEnEuro")
    @ResponseWrapper(localName = "ConversionEnEuroResponse", targetNamespace = "http://ws/", className = "proxy.ConversionEnEuroResponse")
    @Action(input = "http://ws/BanqueService/ConversionEnEuroRequest", output = "http://ws/BanqueService/ConversionEnEuroResponse")
    public double conversionEnEuro(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
